### ISSUE TITLE
在Big sur驱动SATA盘需要增加CtlnaAHCIPort.kext

### ISSUE THREAD

**Issue by snail1126** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#13]
CtlnaAHCIPort.kext
https://github.com/dortania/OpenCore-Install-Guide/blob/master/extra-files/CtlnaAHCIPort.kext.zip
非常重要的一个驱动，在Big sur系统上更改了控制器，SATA盘需要此驱动
未使用此驱动会出现如下错误（个人经验）
卡在 disk2 device is write locked
出现 进入安装界面找不到硬盘的情况
但在Catalina版本上可以不使用此驱动

**Comment by CLAY-BIOS** [comment]
> CtlnaAHCIPort.kext
> https://github.com/dortania/OpenCore-Install-Guide/blob/master/extra-files/CtlnaAHCIPort.kext.zip
> 非常重要的一个驱动，在Big sur系统上更改了控制器，SATA盘需要此驱动
> 未使用此驱动会出现如下错误（个人经验）
> 卡在 disk2 device is write locked
> 出现 进入安装界面找不到硬盘的情况
> 但在Catalina版本上可以不使用此驱动

谢谢你的建议，我会在后面的更新中添加。
