### ISSUE TITLE
请问下DP下4K输出有解么？还有UltraDock貌似也不支持

### ISSUE THREAD

**Issue by snail1126** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#14]
更新了最新版的OC，还有集成Sata驱动，目前主机基本完美使用了。
不过DP外接显示器只能最高2k分辨率，目测是DVMT分配显存的问题，这块有解么？
另外，UltraDock除了充电和USB口外，可否有支持的计划和方案？

**Comment by CLAY-BIOS** [comment]
> 更新了最新版的OC，还有集成Sata驱动，目前主机基本完美使用了。
> 不过DP外接显示器只能最高2k分辨率，目测是DVMT分配显存的问题，这块有解么？
> 另外，UltraDock除了充电和USB口外，可否有支持的计划和方案？

4k显示器目前的解决方法：
需要解锁bios高级菜单，把dvmt改成128m，调整stolenmem超过64m，外接显示器可以达到4k。
UltraDock目前没有支持计划。

**Comment by snail1126** [comment]
解锁bios高级菜单需要解码器刷写BIOS，要求有点高。那核心就是DVMT，我再考虑下其他方案，多谢～

**Comment by CLAY-BIOS** [comment]
> 解锁bios高级菜单需要解码器刷写BIOS，要求有点高。那核心就是DVMT，我再考虑下其他方案，多谢～

你可以试一下这个config文件，我尝试加入了一些DVMT相关的补丁，但我没有4k显示器来测试。
[config.plist.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5702056/config.plist.zip)
