### ISSUE TITLE
Sleep not working on last config

### ISSUE THREAD

**Issue by dimka4996** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#15]
I've updated your config on my x250 and now laptop goes to sleep and wakes recursively when lid closed, can you revert to pervious  config?

**Comment by CLAY-BIOS** [comment]
> I've updated your config on my x250 and now laptop goes to sleep and wakes recursively when lid closed, can you revert to pervious config?

This is the previous version.
[Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5707354/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip)
Execute at the terminal：log show --last boot | grep -Ei "Wake reason"
I'd like to see what causes the arousal.

**Comment by dimka4996** [comment]
I must also say that I do not use dw1820a, I'm still waiting for him from aliexpress. I use itwlm kext for my stock wifi. I deleted device properties for dw1820a, bootargs and kexts which he uses. Soon I will make a command in the terminal. 

Sorry for the bad English, I'm from Ukraine and I'm writing through a translator from Google.

**Comment by dimka4996** [comment]
![20201217_085023](https://user-images.githubusercontent.com/73780911/102453476-f2c6ca00-4044-11eb-90b4-be15a10a854c.jpg)
Sorry for photo, I've tried vanilla config without any changes see what changes. this is what the command gives

**Comment by dimka4996** [comment]
https://github.com/shmilee/T450-Hackintosh#dsdt-wake-fix I've do some research, what about this?

**Comment by CLAY-BIOS** [comment]
> ![20201217_085023](https://user-images.githubusercontent.com/73780911/102453476-f2c6ca00-4044-11eb-90b4-be15a10a854c.jpg)
> Sorry for photo, I've tried vanilla config without any changes see what changes. this is what the command gives

Incomplete log.
Try to execute at the terminal: log show --last 12h | grep -Ei "Wake reason"
Also, can you describe the problem in detail?

**Comment by dimka4996** [comment]
I made video for you with my issue https://youtu.be/1-jYTcfgQkg

**Comment by CLAY-BIOS** [comment]
> I made video for you with my issue https://youtu.be/1-jYTcfgQkg
> 
> Or on the cloud https://1drv.ms/v/s!AtNCK0HHp2Ybhbh47tjS2uwhth5zCQ

Try this EFI file
[EFI 2.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708146/EFI.2.zip)

**Comment by dimka4996** [comment]
> > I made video for you with my issue https://youtu.be/1-jYTcfgQkg
> > Or on the cloud https://1drv.ms/v/s!AtNCK0HHp2Ybhbh47tjS2uwhth5zCQ
> 
> Try this EFI file
> [EFI 2.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708146/EFI.2.zip)

Those efi have same issue



> > I've updated your config on my x250 and now laptop goes to sleep and wakes recursively when lid closed, can you revert to pervious config?
> 
> This is the previous version.
> [Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5707354/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip)
> Execute at the terminal：log show --last boot | grep -Ei "Wake reason"
> I'd like to see what causes the arousal.

But this works perfectly

**Comment by CLAY-BIOS** [comment]
> > > I made video for you with my issue https://youtu.be/1-jYTcfgQkg
> > > Or on the cloud https://1drv.ms/v/s!AtNCK0HHp2Ybhbh47tjS2uwhth5zCQ
> > 
> > 
> > Try this EFI file
> > [EFI 2.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708146/EFI.2.zip)
> 
> Those efi have same issue
> 
> > > I've updated your config on my x250 and now laptop goes to sleep and wakes recursively when lid closed, can you revert to pervious config?
> > 
> > 
> > This is the previous version.
> > [Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5707354/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip)
> > Execute at the terminal：log show --last boot | grep -Ei "Wake reason"
> > I'd like to see what causes the arousal.
> 
> But this works perfectly

This is a USB problem.
Can you provide me with a screenshot of hackintkool-> USB?
[Hackintool.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708349/Hackintool.zip)

**Comment by dimka4996** [comment]
> > > > I made video for you with my issue https://youtu.be/1-jYTcfgQkg
> > > > Or on the cloud https://1drv.ms/v/s!AtNCK0HHp2Ybhbh47tjS2uwhth5zCQ
> > > 
> > > 
> > > Try this EFI file
> > > [EFI 2.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708146/EFI.2.zip)
> > 
> > 
> > Those efi have same issue
> > > > I've updated your config on my x250 and now laptop goes to sleep and wakes recursively when lid closed, can you revert to pervious config?
> > > 
> > > 
> > > This is the previous version.
> > > [Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5707354/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip)
> > > Execute at the terminal：log show --last boot | grep -Ei "Wake reason"
> > > I'd like to see what causes the arousal.
> > 
> > 
> > But this works perfectly
> 
> This is a USB problem.
> Can you provide me with a screenshot of hackintkool-> USB?
> [Hackintool.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708349/Hackintool.zip)

yes, here is
![Снимок экрана 2020-12-17 в 12 03 26](https://user-images.githubusercontent.com/73780911/102473637-5a3e4300-4060-11eb-941d-c69e2d57f3f8.png)
![Снимок экрана 2020-12-17 в 12 03 30](https://user-images.githubusercontent.com/73780911/102473654-63c7ab00-4060-11eb-8c2d-d55f46944502.png)

**Comment by CLAY-BIOS** [comment]
> > > > > I made video for you with my issue https://youtu.be/1-jYTcfgQkg
> > > > > Or on the cloud https://1drv.ms/v/s!AtNCK0HHp2Ybhbh47tjS2uwhth5zCQ
> > > > 
> > > > 
> > > > Try this EFI file
> > > > [EFI 2.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708146/EFI.2.zip)
> > > 
> > > 
> > > Those efi have same issue
> > > > > I've updated your config on my x250 and now laptop goes to sleep and wakes recursively when lid closed, can you revert to pervious config?
> > > > 
> > > > 
> > > > This is the previous version.
> > > > [Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5707354/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip)
> > > > Execute at the terminal：log show --last boot | grep -Ei "Wake reason"
> > > > I'd like to see what causes the arousal.
> > > 
> > > 
> > > But this works perfectly
> > 
> > 
> > This is a USB problem.
> > Can you provide me with a screenshot of hackintkool-> USB?
> > [Hackintool.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708349/Hackintool.zip)
> 
> yes, here is
> ![Снимок экрана 2020-12-17 в 12 03 26](https://user-images.githubusercontent.com/73780911/102473637-5a3e4300-4060-11eb-941d-c69e2d57f3f8.png)
> ![Снимок экрана 2020-12-17 в 12 03 30](https://user-images.githubusercontent.com/73780911/102473654-63c7ab00-4060-11eb-8c2d-d55f46944502.png)

I see the problem. There is a 4G card in your X250. I didn't take that into account.
This EFI should no longer be a problem.
[EFI-QS.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708646/EFI-QS.zip)

**Comment by dimka4996** [comment]
I can remove the 4g card, with dw1820a I'm also waiting m.2 ssd

**Comment by CLAY-BIOS** [comment]
> > > > > > I made video for you with my issue https://youtu.be/1-jYTcfgQkg
> > > > > > Or on the cloud https://1drv.ms/v/s!AtNCK0HHp2Ybhbh47tjS2uwhth5zCQ
> > > > > 
> > > > > 
> > > > > Try this EFI file
> > > > > [EFI 2.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708146/EFI.2.zip)
> > > > 
> > > > 
> > > > Those efi have same issue
> > > > > > I've updated your config on my x250 and now laptop goes to sleep and wakes recursively when lid closed, can you revert to pervious config?
> > > > > 
> > > > > 
> > > > > This is the previous version.
> > > > > [Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5707354/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore-95fd02216315e00b3cdf12bcee9e0b9b3e0b66d1.zip)
> > > > > Execute at the terminal：log show --last boot | grep -Ei "Wake reason"
> > > > > I'd like to see what causes the arousal.
> > > > 
> > > > 
> > > > But this works perfectly
> > > 
> > > 
> > > This is a USB problem.
> > > Can you provide me with a screenshot of hackintkool-> USB?
> > > [Hackintool.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708349/Hackintool.zip)
> > 
> > 
> > yes, here is
> > ![Снимок экрана 2020-12-17 в 12 03 26](https://user-images.githubusercontent.com/73780911/102473637-5a3e4300-4060-11eb-941d-c69e2d57f3f8.png)
> > ![Снимок экрана 2020-12-17 в 12 03 30](https://user-images.githubusercontent.com/73780911/102473654-63c7ab00-4060-11eb-8c2d-d55f46944502.png)
> 
> I see the problem. There is a 4G card in your X250. I didn't take that into account.
> This EFI is no longer a problem.
> [EFI-QS.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5708646/EFI-QS.zip)

I have made changes to EFI, you don't need to take out the 4g network card.
Does this EFI work properly?

**Comment by dimka4996** [comment]
Yea, i tested with your fixed EFI-QS, works nice, than i take out 4g card(it's not working in macos and i be able to replace those with m.2 ssd) and tested with release efi, works too, thanks!

**Comment by dimka4996** [comment]
Do you merge those fix for cards with your next release?

**Comment by CLAY-BIOS** [comment]
> Do you merge those fix for cards with your next release?

yes,I'll update later.
