### ISSUE TITLE
Wifi cannot be turned on after upgrading to latest OC

### ISSUE THREAD

**Issue by mybabysexy** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#17]
Hi,

After updating files from the last commit (2 days ago), my wifi card stopped working and cannot be turned on (which still works fine on the last version) and not recognized by MacOS.

My card: bcm94360cs2

![image](https://user-images.githubusercontent.com/20596043/102895495-5e6ec400-4497-11eb-90b5-901a29c7dc0d.png)
This is the screenshot from the last version

![image](https://user-images.githubusercontent.com/20596043/102895956-3895ef00-4498-11eb-96a0-8f1640db4abf.png)
New version lacks of Interfaces en1

**Comment by mybabysexy** [comment]
Well, after comparing `config.plist`, `AirportBrcmFixup.kext/Contents/PlugIns/AirPortBrcmNIC_Injector.kext` is disabled in the new commit. I enabled that and my wifi card works again.
![image](https://user-images.githubusercontent.com/20596043/102898516-32097680-449c-11eb-91dd-41537fedf367.png)

Please change that back so future users won't have any problems with their wifi.

**Comment by CLAY-BIOS** [comment]
> Well, after comparing `config.plist`, `AirportBrcmFixup.kext/Contents/PlugIns/AirPortBrcmNIC_Injector.kext` is disabled in the new commit. I enabled that and my wifi card works again.
> ![image](https://user-images.githubusercontent.com/20596043/102898516-32097680-449c-11eb-91dd-41537fedf367.png)
> 
> Please change that back so future users won't have any problems with their wifi.

I'll fix that in a later update
