### ISSUE TITLE
Some cosmetics

### ISSUE THREAD

**Issue by dimka4996** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#19]
Hi, you can add all bootagrs in device properties of the sound and wifi

`brcmfx-country - string - #a`

But audio also requires delay to start, because on my x250 AppleALC working inconsistently

`layout-id - data - <20000000>`
`alc-delay - number - 800`

**Comment by CLAY-BIOS** [comment]
> Hi, you can add all bootagrs in device properties of the sound and wifi
> 
> `brcmfx-country - string - #a`
> 
> But audio also requires delay to start, because on my x250 AppleALC working inconsistently
> 
> `layout-id - data - <20000000>`
> `alc-delay - number - 800`

Thank you for your suggestion, I will add it in a later update.
