### ISSUE TITLE
关于声卡

### ISSUE THREAD

**Issue by Mark-William213** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#2]
我的内置扬声器听音乐了一段时间后就没声了 线路输出是正常的

**Comment by Mark-William213** [comment]
俩种都尝试了 还是。。。他这个睡眠后不使用就没有声音了  需要重新开机才好。。

**Comment by CLAY-BIOS** [comment]
> 俩种都尝试了 还是。。。他这个睡眠后不使用就没有声音了 需要重新开机才好。。

我刚刚更新了新的方法 请尝试

**Comment by Mark-William213** [comment]
是不是oc引导cpu变频不是很好 我觉得运行起来很发烫阿 风扇声音蛮大的

**Comment by CLAY-BIOS** [comment]
> 是不是oc引导cpu变频不是很好 我觉得运行起来很发烫阿 风扇声音蛮大的

你使用的t450s cpu是 i5 还是 i7?

**Comment by Mark-William213** [comment]
跟你一样的 i7 5600u  8G运行。。。 话说你的那个20G是写进去的吧。。

**Comment by CLAY-BIOS** [comment]
> 跟你一样的 i7 5600u 8G运行； 话说你的那个20G是写进去的吧。

我认为不是变频的问题，请检查后台是否有程序占用大量CPU。
20GB内存是因为我使用了一根单条16GB的内存条，加上主板上的4GB 一共20GB。

**Comment by Mark-William213** [comment]
好的 T450s 的内存条是不是分单卡槽和双卡槽阿 我的貌似是单 拆机看过
