### ISSUE TITLE
如何警用鼠标唤醒

### ISSUE THREAD

**Issue by lost1984** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#20]
感谢大佬，T450S+7260wifi ，能够正常启动和使用，并且休眠也正常。
但是，休眠状态，无论是否盒盖，鼠标都会一碰就唤醒，这个能否帮忙解决一下吗？

**Comment by CLAY-BIOS** [comment]
> 感谢大佬，T450S+7260wifi ，能够正常启动和使用，并且休眠也正常。
> 但是，休眠状态，无论是否盒盖，鼠标都会一碰就唤醒，这个能否帮忙解决一下吗？

我猜你应该是使用的无线鼠标，因为有线鼠标不会有这个问题。
1.如果你使用的鼠标是通过蓝牙连接，请在蓝牙中关闭蓝牙设备唤醒。
![截屏2020-12-29 16 22 00](https://user-images.githubusercontent.com/54008255/103272603-3f70b480-49f8-11eb-89c6-c8ad260b252b.png)

2.如果你使用的鼠标是通过USB连接，你可以使用此EFI文件。这个版本禁用了外置设备唤醒。
[EFI-f.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5750130/EFI-f.zip)

此问题不会修复，因为白苹果也一样。

**Comment by lost1984** [comment]
感谢你的快速，认真回答。目前我的是无线适配器的鼠标，测试了上面的efi-f 文件，已经很ok。
