### ISSUE TITLE
更换EFI后出现如下图问题：该如何解决？

### ISSUE THREAD

**Issue by zhangyongen** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#21]
http://bbs.pcbeta.com/data/attachment/forum/202101/03/133318qcjq8shjj4eqj6cy.jpg

**Comment by CLAY-BIOS** [comment]
> http://bbs.pcbeta.com/data/attachment/forum/202101/03/133318qcjq8shjj4eqj6cy.jpg
在引导界面选择 Reset NVRAM重置NVRAM
