### ISSUE TITLE
SD Cardreader not working after sleep

### ISSUE THREAD

**Issue by dimka4996** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#22]
Hi, the whole problem is in the header, the card reader disappears from the system after the laptop sleeps. Tried a couple kext from sinetek and modified from other developers, the problem is the same. Maybe problem in acpi, and it's requires some patch. I'm not very good at acpi maybe you can solve this problem.

**Comment by CLAY-BIOS** [comment]
> Hi, the whole problem is in the header, the card reader disappears from the system after the laptop sleeps. Tried a couple kext from sinetek and modified from other developers, the problem is the same. Maybe problem in acpi, and it's requires some patch. I'm not very good at acpi maybe you can solve this problem.

This is a problem with Sinetek-rtsx.kext, it does not work properly in maos Big Sur unless someone rewrites it.
You can try to put Sinetek-rtsx.kext into the Library /Extensions directory.

**Comment by dimka4996** [comment]
Not working, kext not loading from /L/E

**Comment by CLAY-BIOS** [comment]
> Not working, kext not loading from /L/E

hi! I made some changes to sinetek-rtsx. kext, you can test it.
[Sinetek-rtsx.kext.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5874870/Sinetek-rtsx.kext.zip)

**Comment by dimka4996** [comment]
Cardreader reloading after sleep, but it works, thanks!
