### ISSUE TITLE
Update to OpenCore 0.6.5

### ISSUE THREAD

**Issue by dimka4996** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#23]

**Comment by i3p9** [comment]
Hey, just to let you know @CLAY-BIOS does this with his own time. And you already know 0.6.5 was just released. So let him take his time and update to the latest 0.6.5. 

Also, 0.6.4 was already a very solid release, you don’t *need* to update to 0.6.5 right away. Cheers!

**Comment by dimka4996** [comment]
> Hey, just to let you know @CLAY-BIOS does this with his own time. And you already know 0.6.5 was just released. So let him take his time and update to the latest 0.6.5.
> 
> Also, 0.6.4 was already a very solid release, you don’t _need_ to update to 0.6.5 right away. Cheers!

Hey. I know, many thanks to him, if I could update myself - I would help him, just if he accidentally missed the release, then I just remind him. can one of the config users will be able to update and offer him his changes
