### ISSUE TITLE
x250 一直无法使用读卡器和添加AirportItlwm.kext

### ISSUE THREAD

**Issue by klzbw** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#24]
使用大哥提供个opencore 的6.5  EFI ，因为我网卡就是原装机网卡,只能使用heliport+itlwm.kext ，单独无法使用AirportItlwm.kext，会出现灰Wi-Fi图标。同时我的读卡器也不能工作，望大哥指导下！

**Comment by CLAY-BIOS** [comment]
> 使用大哥提供个opencore 的6.5 EFI ，因为我网卡就是原装机网卡,只能使用heliport+itlwm.kext ，单独无法使用AirportItlwm.kext，会出现灰Wi-Fi图标。同时我的读卡器也不能工作，望大哥指导下！

1.告诉我你的系统版本。
2.读卡器在Windows中能否正常使用？

**Comment by klzbw** [comment]
系统为Catalina。15.7，无法使用AirportItlwm.kext
读卡器在Windows下好像也用不了，可能是我SD卡问题

**Comment by CLAY-BIOS** [comment]
> 系统为Catalina。15.7，无法使用AirportItlwm.kext
> 读卡器在Windows下好像也用不了，可能是我SD卡问题

使用这个config文件和AirportItlwm.kext，替换掉原来的文件。
[config.plist.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5780505/config.plist.zip)
[AirportItlwm.kext.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5780511/AirportItlwm.kext.zip)
