### ISSUE TITLE
T450开机出现reset nvram图标，回车后重启，一直循环

### ISSUE THREAD

**Issue by albert2lyu** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#25]

**Comment by CLAY-BIOS** [comment]
> No description provided.

你能详细描述一下这个问题吗?

**Comment by albert2lyu** [comment]
用gibMaoc做好启动盘，将这个efi目录拷贝到u盘，在T450上，开机重u盘启动，界面出现reset
nvram图标，其他按键都无效，只有回车，回车后重启，再启动也是这样
收件箱

辨识 <notifications@github.com> 于2021年1月7日周四 下午5:04写道：

**Comment by CLAY-BIOS** [comment]
> 用gibMaoc做好启动盘，将这个efi目录拷贝到u盘，在T450上，开机重u盘启动，界面出现reset nvram图标，其他按键都无效，只有回车，回车后重启，再启动也是这样 收件箱 辨识 <notifications@github.com> 于2021年1月7日周四 下午5:04写道：
> […](#)
开机界面肯定会出现reset nvram图标，你选择reset nvram回车肯定会重启，这没问题啊。
如果开机只有reset nvram图标的话，是你启动盘的问题，与EFI文件无关。
