### ISSUE TITLE
死机

### ISSUE THREAD

**Issue by Mark-William213** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#26]
大佬有没有遇到无缘无故死机了 之前以为是关闭sip导致 现在开启后最长运行一俩天后遇到

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Mark-William213** [comment]
重启后一切正常 是否与efi文件有关 我一直都在更新着 电脑配置都一样 除了内存8Ghhhhh

**Comment by CLAY-BIOS** [comment]
> 重启后一切正常 是否与efi文件有关 我一直都在更新着 电脑配置都一样 除了内存8Ghhhhh

我没有遇到你说的问题。
如果你有相关日志，可以把它发送上来。

**Comment by Mark-William213** [comment]
![1345137C2C567CF38F43818BA4A0A96B](https://user-images.githubusercontent.com/56502655/104090005-7d01f700-52ae-11eb-992a-f240b813e1e8.png)
![Uploading 720A681B064FCD28D718226BB4DFBAE0.png…]()

**Comment by Mark-William213** [comment]
可以看得到嘛？ 好像需要科学...

**Comment by Mark-William213** [comment]
![Uploading 720A681B064FCD28D718226BB4DFBAE0.png…]()

**Comment by Mark-William213** [comment]
![720A681B064FCD28D718226BB4DFBAE0](https://user-images.githubusercontent.com/56502655/104090289-c4898280-52b0-11eb-9c17-3ef6ee79f339.png)

**Comment by CLAY-BIOS** [comment]
> 可以看得到嘛？ 好像需要科学...

更具日志来看是com.apple.driver.watchdog导致的kp。
你是否修改过系统文件？
1.使用CleanMyMac X对系统进行清理。
2.在引导界面选择Reset NVRAM重置NVRAM

**Comment by Mark-William213** [comment]
修改过pd 虚拟机配置参数文件算嘛…… 其他没什么了

**Comment by Mark-William213** [comment]
![71898F44-1EDC-478D-BB34-6A149C1ED441](https://user-images.githubusercontent.com/56502655/104092251-a8d8a900-52bd-11eb-9402-cae70dc7aa73.jpeg)
![89FDF513-000F-47CE-B9F9-29FC7AB037E5](https://user-images.githubusercontent.com/56502655/104092256-b2faa780-52bd-11eb-97a1-fb2adbf36da2.jpeg)

**Comment by Mark-William213** [comment]
就在刚刚又发生了

**Comment by CLAY-BIOS** [comment]
> 就在刚刚又发生了...半天还没坚持到

![截屏2021-01-09 21 58 24](https://user-images.githubusercontent.com/54008255/104093520-ec371580-52c5-11eb-8acd-ec690f67394a.png)
磁盘错误导致的关机，请检查你的磁盘。
