### ISSUE TITLE
Low volume on x250

### ISSUE THREAD

**Issue by dimka4996** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#27]
After sleep laptop has too low volume, but in Settings it's set to 100%.

**Comment by CLAY-BIOS** [comment]
> After sleep laptop has too low volume, but in Settings it's set to 100%.

I'm sorry, I didn't have that problem.

**Comment by dimka4996** [comment]
I've solved this problem by choosing right AppleALC layout for our laptop, info found on AppleALC release page.
![Uploading 20210126_090448.jpg…]()
