### ISSUE TITLE
Touchpad not working under macos 10.13.6

### ISSUE THREAD

**Issue by dimka4996** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#29]
Hello. I know that this is not included in this configuration, it is for another system, but I needed to put the system older and the touchpad does not work there (and perhaps something else).do you know how to solve this problem?

**Comment by CLAY-BIOS** [comment]
> Hello. I know that this is not included in this configuration, it is for another system, but I needed to put the system older and the touchpad does not work there (and perhaps something else).do you know how to solve this problem?

In the current version I use voodoosmbus.kext + voodoormi.kext to drive the Touch pad.
https://github.com/VoodooSMBus/VoodooRMI
You can try removing voodoosmbus.kext + voodoormi.kext to use voodoops2controller.kext to drive the Touch pad,macOS 10.13 An early version may be required.
https://github.com/acidanthera/VoodooPS2

**Comment by dimka4996** [comment]
Thank you, I'll try it and reply later
