### ISSUE TITLE
求助：安装时可以进入系统，重启时报错

### ISSUE THREAD

**Issue by 8atm4n** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#30]
显示如下：
![0fd6a0d6fc5c29d3a1737462854cd91](https://user-images.githubusercontent.com/11907725/107365691-1d4e7400-6b18-11eb-9900-692082921175.jpg)
![2957748f44fb4f689b6d0750909c5be](https://user-images.githubusercontent.com/11907725/107365700-1fb0ce00-6b18-11eb-890b-5831adf71d83.jpg)

**Comment by CLAY-BIOS** [comment]
> 显示如下：
> ![0fd6a0d6fc5c29d3a1737462854cd91](https://user-images.githubusercontent.com/11907725/107365691-1d4e7400-6b18-11eb-9900-692082921175.jpg)
> ![2957748f44fb4f689b6d0750909c5be](https://user-images.githubusercontent.com/11907725/107365700-1fb0ce00-6b18-11eb-890b-5831adf71d83.jpg)

选择reset nvram清除nvram，如果无效，请检查你的BIOS设置。

**Comment by 8atm4n** [comment]
感谢答复，重装后成功进入系统～
