### ISSUE TITLE
Fn key issues in W10 since OC 0.6.6 release

### ISSUE THREAD

**Issue by nycxbro527** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#34]
First, thank you for all your hard work! You EFI package is amazing - if I can contribute using Paypal or some other means let me know. Ever since the introduction of your OC 0.6.6 package, with the exception of the volume =/- button, all other function keys are very slow (latency) in Windows 10 (e.g. Brightness +/-, Mic mute, search) specifically F4-F12. I tried all your OC 0.6.6 packages (v1,v2,v2.1). Your OC 0.6.5 package does not have this problem so I've been sticking with that. Is this an issue with OC 0.6.6 or something you changed in the EFI?

**Comment by CLAY-BIOS** [comment]
> First, thank you for all your hard work! You EFI package is amazing - if I can contribute using Paypal or some other means let me know. Ever since the introduction of your OC 0.6.6 package, with the exception of the volume =/- button, all other function keys are very slow (latency) in Windows 10 (e.g. Brightness +/-, Mic mute, search) specifically F4-F12. I tried all your OC 0.6.6 packages (v1,v2,v2.1). Your OC 0.6.5 package does not have this problem so I've been sticking with that. Is this an issue with OC 0.6.6 or something you changed in the EFI?

I have noticed that this problem is caused by a new battery patch.
I have fixed it.
I will release a new version later.

**Comment by nycxbro527** [comment]
thank you

**Comment by CLAY-BIOS** [comment]
> thank you
i see You reopened this question
Has the problem been solved?

**Comment by CLAY-BIOS** [comment]
> thank you

i see You reopened this question
Has the problem been solved?

**Comment by nycxbro527** [comment]
No, I tried your most recent release (OC 0.6.6 v2.2) and the same issue. It works on the initial reboot but then issue reoccurs. Was gonna try to use your 0.6.5 release and upgrade to OC 0.6.6 from there, but noticed some changes in the config.plist that I need to update.

**Comment by CLAY-BIOS** [comment]
> No, I tried your most recent release (OC 0.6.6 v2.2) and the same issue. It works on the initial reboot but then issue reoccurs. Was gonna try to use your 0.6.5 release and upgrade to OC 0.6.6 from there, but noticed some changes in the config.plist that I need to update.

Strange, I tested it on T450S and there is no such problem.
You can try to select in the boot interface reset nvram.

**Comment by nycxbro527** [comment]
My newbie mistake - sorry. I was using ProperTree & OC Snapshot since I had to edit some kexts (I use itlwm) and remove the Tools. It was picking up the old battery patch folder you left in ACPI.
