### ISSUE TITLE
关于耳机杂音

### ISSUE THREAD

**Issue by nogi6purple** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#35]
设备t450，win10双系统。
外放无问题，插上耳机开机即杂音。
前期休眠存在问题，更新驱动后，耳机问题可在休眠后修复。

另外双系统手机无法连接系统蓝牙，望有人回答

**Comment by CLAY-BIOS** [comment]
> 设备t450，win10双系统。
> 外放无问题，插上耳机开机即杂音。
> 前期休眠存在问题，更新驱动后，耳机问题可在休眠后修复。
> 
> 另外双系统手机无法连接系统蓝牙，望有人回答

1.你有没有使用ALCPlugFix来修复耳机？
2.告诉我你的系统版本和无线网卡型号。

**Comment by nogi6purple** [comment]
> > 设备t450，win10双系统。
> > 外放无问题，插上耳机开机即杂音。
> > 前期休眠存在问题，更新驱动后，耳机问题可在休眠后修复。
> > 另外双系统手机无法连接系统蓝牙，望有人回答
> 
> 1.你有没有使用ALCPlugFix来修复耳机？
> 2.告诉我你的系统版本和无线网卡型号。

1.文件夹内ALCPlugFix和hda-verb我都运行过
2.系统为Big Sur 11.2.3无线网卡为intel 7265N

**Comment by CLAY-BIOS** [comment]
> > > 设备t450，win10双系统。
> > > 外放无问题，插上耳机开机即杂音。
> > > 前期休眠存在问题，更新驱动后，耳机问题可在休眠后修复。
> > > 另外双系统手机无法连接系统蓝牙，望有人回答
> > 
> > 
> > 1.你有没有使用ALCPlugFix来修复耳机？
> > 2.告诉我你的系统版本和无线网卡型号。
> 
> 1.文件夹内ALCPlugFix和hda-verb我都运行过
> 2.系统为Big Sur 11.2.3无线网卡为intel 7265N

1.ALCPlugFix脚本我已经测试过了，没有发现你说的问题，如果你之前使用过其它版本的ALCPlugFix，请先卸载它。
请确认你是否使用了正确的修复方式。
如图：
在终端CD 到 ALCPlugFix 文件目录
然后执行 ./install.sh 或者 sudo ./install.sh
如果出现 Done！就说明脚本执行成功。
![截屏2021-03-16 下午8 03 58](https://user-images.githubusercontent.com/54008255/111307276-2e991c00-8694-11eb-9238-ffe5e76fa0a0.png)
2.intel 7XXX 系列的无线网卡 蓝牙不能与Wi-Fi同时使用，如果你要使用蓝牙需要先关闭Wi-Fi。你可以通过升级intel 8系网卡来解决这个问题（例如：intel 8265）

**Comment by nogi6purple** [comment]
> > > > 设备t450，win10双系统。
> > > > 外放无问题，插上耳机开机即杂音。
> > > > 前期休眠存在问题，更新驱动后，耳机问题可在休眠后修复。
> > > > 另外双系统手机无法连接系统蓝牙，望有人回答
> > > 
> > > 
> > > 1.你有没有使用ALCPlugFix来修复耳机？
> > > 2.告诉我你的系统版本和无线网卡型号。
> > 
> > 
> > 1.文件夹内ALCPlugFix和hda-verb我都运行过
> > 2.系统为Big Sur 11.2.3无线网卡为intel 7265N
> 
> 1.ALCPlugFix脚本我已经测试过了，没有发现你说的问题，如果你之前使用过其它版本的ALCPlugFix，请先卸载它。
> 请确认你是否使用了正确的修复方式。
> 如图：
> 在终端CD 到 ALCPlugFix 文件目录
> 然后执行 ./install.sh 或者 sudo ./install.sh
> 如果出现 Done！就说明脚本执行成功。
> ![截屏2021-03-16 下午8 03 58](https://user-images.githubusercontent.com/54008255/111307276-2e991c00-8694-11eb-9238-ffe5e76fa0a0.png)
> 2.intel 7XXX 系列的无线网卡 蓝牙不能与Wi-Fi同时使用，如果你要使用蓝牙需要先关闭Wi-Fi。你可以通过升级intel 8系网卡来解决这个问题（例如：intel 8265）

1.耳机问题完美修复
2.关闭了wifi蓝牙还是不ok，还好蓝牙不是刚需
3.休眠唤醒时而成功，感觉像玄学一样。大多数情况都是开盖屏幕光亮无画面，输入有提示音反馈。

**Comment by CLAY-BIOS** [comment]
> > > > > 设备t450，win10双系统。
> > > > > 外放无问题，插上耳机开机即杂音。
> > > > > 前期休眠存在问题，更新驱动后，耳机问题可在休眠后修复。
> > > > > 另外双系统手机无法连接系统蓝牙，望有人回答
> > > > 
> > > > 
> > > > 1.你有没有使用ALCPlugFix来修复耳机？
> > > > 2.告诉我你的系统版本和无线网卡型号。
> > > 
> > > 
> > > 1.文件夹内ALCPlugFix和hda-verb我都运行过
> > > 2.系统为Big Sur 11.2.3无线网卡为intel 7265N
> > 
> > 
> > 1.ALCPlugFix脚本我已经测试过了，没有发现你说的问题，如果你之前使用过其它版本的ALCPlugFix，请先卸载它。
> > 请确认你是否使用了正确的修复方式。
> > 如图：
> > 在终端CD 到 ALCPlugFix 文件目录
> > 然后执行 ./install.sh 或者 sudo ./install.sh
> > 如果出现 Done！就说明脚本执行成功。
> > ![截屏2021-03-16 下午8 03 58](https://user-images.githubusercontent.com/54008255/111307276-2e991c00-8694-11eb-9238-ffe5e76fa0a0.png)
> > 2.intel 7XXX 系列的无线网卡 蓝牙不能与Wi-Fi同时使用，如果你要使用蓝牙需要先关闭Wi-Fi。你可以通过升级intel 8系网卡来解决这个问题（例如：intel 8265）
> 
> 1.耳机问题完美修复
> 2.关闭了wifi蓝牙还是不ok，还好蓝牙不是刚需
> 3.休眠唤醒时而成功，感觉像玄学一样。大多数情况都是开盖屏幕光亮无画面，输入有提示音反馈。

尝试在引导界面选择reset nvram清除一下nvram，或者检查一下你的BIOS设置。
