### ISSUE TITLE
DW1820A Driver (for Windows)

### ISSUE THREAD

**Issue by i3p9** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#36]
Since it's not natively supported, I have tried multiple drivers like from [dell](https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=myjhh), [github](https://github.com/ameeno/DELL-DW1820A-Drivers) and from [daliansky](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html) and none of them seem to work.

Since you have the same card, what steps did you take to run dw1820A in Windows 10? Specially wifi since it's necessary. My version is `DW1820A 00JT494`

Thanks!

**Comment by CLAY-BIOS** [comment]
> Since it's not natively supported, I have tried multiple drivers like from [dell](https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=myjhh), [github](https://github.com/ameeno/DELL-DW1820A-Drivers) and from [daliansky](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html) and none of them seem to work.
> 
> Since you have the same card, what steps did you take to run dw1820A in Windows 10? Specially wifi since it's necessary. My version is `DW1820A 00JT494`
> 
> Thanks!

Unzip the driver.(One from Broadcom, the other from Dell)
[Broadcom_94350_WiFi_Win10_x64.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6201471/Broadcom_94350_WiFi_Win10_x64.zip)
[Dell DW1820A_1830_WiFi_Win10_x64.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6201473/Dell.DW1820A_1830_WiFi_Win10_x64.zip)
In the device manager, right-click to update the driver to manually find and install the driver. After selecting the decompression directory, the driver will be searched automatically.

**Comment by i3p9** [comment]
Thank you. The first link worked for me. I have tried the others which didn’t work. Thanks again!

**Comment by juanpy0223** [comment]
Please confirm that dw1820a finds networks on windows 10
