### ISSUE TITLE
笔记本2k内屏黑屏

### ISSUE THREAD

**Issue by bra-daydayup** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#38]
如题，自带的2k内屏无法点亮，跑完代码闪了一下苹果图标就黑屏了（屏幕亮，显示黑色），尝试过盒盖睡眠再打开，没有效果，依然黑屏，机型是x1carbon 2015（3rd）

**Comment by CLAY-BIOS** [comment]
> 如题，自带的2k内屏无法点亮，跑完代码闪了一下苹果图标就黑屏了（屏幕亮，显示黑色），尝试过盒盖睡眠再打开，没有效果，依然黑屏，机型是x1carbon 2015（3rd）

此问题似乎与 #37 一样，但我不清楚什么地方出了问题。
外接显示器是否可以正常使用？
你可以试一试以前的版本，看看有没有这个问题
https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/releases/tag/OpenCore-0.6.6-v2.0
