### ISSUE TITLE
External Monitor with miniDP black screen

### ISSUE THREAD

**Issue by alibekissakul** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#39]
Hello @CLAY-BIOS 

First, I thank you for this repo, and work you doing hard here 👏👏

I found a little problem, when I connect Monitor with miniDP, the system crashes, if system is running, after connect miniDP here a black screen and not response from notebook, or if I launch notebook with miniDP, here a cyclic reboot. 

I'm asking a help with this problem.

Thanks.

**Comment by CLAY-BIOS** [comment]
> Hello @CLAY-BIOS
> 
> First, I thank you for this repo, and work you doing hard here 👏👏
> 
> I found a little problem, when I connect Monitor with miniDP, the system crashes, if system is running, after connect miniDP here a black screen and not response from notebook, or if I launch notebook with miniDP, here a cyclic reboot.
> 
> I'm asking a help with this problem.
> 
> Thanks.

1. Tell me your system version and machine model.
2. Try to select reset NVRAM in the boot interface to clear NVRAM.

**Comment by alibekissakul** [comment]
1.  Thinkpad T450 (HD5500)

I already solved this problem, just remove custom configurations from config.plist about videocard information.

Thanks for reply
