### ISSUE TITLE
电池的ACPI会影响到Windows

### ISSUE THREAD

**Issue by sa-yuki** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#6]
引导Windows进入系统后显示电池不存在

**Comment by CLAY-BIOS** [comment]
> 引导Windows进入系统后显示电池不存在

我想这应该是OC6.1的bug，因为我在OC6.0中没有遇到这个问题。
在opencore configurator 偏好设置中把版本改成MOD分支版然后保存就可以解决。
为了避免折腾，我会在之后的更新中将OC版本退回6.0。

**Comment by sa-yuki** [comment]
我换了个电池ACPI，引导Windows不会有问题
[归档.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Big-Sur-OpenCore/files/5215594/default.zip)

**Comment by chafergrubs** [comment]
is it possible to use this efi on catalina (macOS 10.15.6)?

**Comment by CLAY-BIOS** [comment]
> 是否可以在Catalina（macOS 10.15.6）上使用此efi？

Yes, it supports Catalina

**Comment by chafergrubs** [comment]
Everything works!however during startup I get this message (OCS :No schema for disableLinkeditJettison at 6  index,context <Quirks>) Do you know how I can fix it?

(thank you so much )

**Comment by CLAY-BIOS** [comment]
> Everything works!however during startup I get this message (`OCS :No schema for disableLinkeditJettison at 6 index,context <Quirks>`) Do you know how I can fix it?
> 
> (thank you so much )

Whether I turn on (DisableLinkeditJettison) or not, it will display this prompt.
If you want to remove this prompt, open the config file using Xcode or plistedit por, find (Kernel > Quirks > DisableLinkeditJettison) and delete it.
Deleting it will have no effect on your system.

**Comment by chafergrubs** [comment]
I did what you wrote and everything went perfectly! Thanks for your help!
