### ISSUE TITLE
能提供前一版嗎，新版t450s不管是catalina還是bigsur，都無法開起來。

### ISSUE THREAD

**Issue by 109980549** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#9]

**Comment by CLAY-BIOS** [comment]
> _No description provided._

这是上一版本的文件。
[Lenovo-ThinkPad-T450s-Big-Sur-OpenCore-0.6.2.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Big-Sur-OpenCore/files/5543056/Lenovo-ThinkPad-T450s-Big-Sur-OpenCore-0.6.2.zip)
我并没有遇到你说的问题，目前一切正常。
你能说的更详细一些吗？
尝试在引导界面选择Reset NVRAM。

**Comment by 109980549** [comment]
您好，抱歉這才回復您。

經查是因為三星的SSD的問題，換一顆其他牌子的SSD就都正常了。

感謝您的付出。
在 2020年11月16日 +0800 AM4:21，辨识 <notifications@github.com>，写道：
